# tls-ingressroute.yaml
apiVersion: traefik.io/v2
kind: IngressRoute
metadata:
  name: {{ include "hello-world.fullname" . }}
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`hello.docker.localhost`)
      kind: Rule
      services:
        - name: hello-world
          port: 80
  tls:
    secretName: hello-world